version: "3.8"

services:
  # inception:
  #   build:
  #     context: ../
  #     dockerfile: srcs/requirements/python/Dockerfile
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "5000:5000"
  #   command: ["python3", "app.py"]
  nginx:
    build:
      context: ../
      dockerfile: srcs/requirements/nginx/Dockerfile

# servises:
# build:
# volumes:
# ports:
# command: 