version: "3.8"  # Adjust version if needed

services:
  inception:
    build:
      context: .  # Use the current directory (where the docker-compose.yml resides)
      dockerfile: requirements/python/Dockerfile  # Specify the Dockerfile path
    volumes:
      - .  # Mount the current directory's "app" folder to /app in the container
    ports:
      - "5000"
    command: ["python", "app.py"]