version: "3.8"

services:
  nginx:
    build:
      context: ../
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports: 
      - "443:443"
    env_file:
      - .env
    restart: unless-stopped
  mariadb:
    build:
      context: ../
      dockerfile: srcs/requirements/mariadb/Dockerfile
    ports: 
      - "3306:3306"
    env_file:
      - .env
    restart: unless-stopped

# servises:
# build:
# volumes:
# ports:
# command: 