version: "3.8"

services:

  mariadb:
    container_name: mariadb
    build:
      context: ../
      dockerfile: srcs/requirements/mariadb/Dockerfile
    ports: 
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ../
      dockerfile: srcs/requirements/wordpress/Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    build:
      context: ../
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports: 
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
      - ./nginx-logs:/var/log/nginx
    networks:
      - inception
    restart: unless-stopped

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/lgrimmei/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/lgrimmei/data/wordpress
      o: bind
      type: none
  
networks:
  inception:
    name: inception
