
services:

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ../
      dockerfile: srcs/requirements/mariadb/Dockerfile
    ports: 
      - "3306:3306"
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    environment:
      MDB_PW: /run/secrets/mdb_pw
      MDB_ROOT_PW: /run/secrets/mdb_root_pw
    secrets:
      - mdb_pw
      - mdb_root_pw


  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ../
      dockerfile: srcs/requirements/wordpress/Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    environment:
      MDB_PW: /run/secrets/mdb_pw
      WP_ADMIN_PW: /run/secrets/wp_admin_pw
      WP_USER_PW: /run/secrets/wp_user_pw
    secrets:
      - mdb_pw
      - wp_admin_pw
      - wp_user_pw
    
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ../
      dockerfile: srcs/requirements/nginx/Dockerfile
    ports: 
      - "443:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - key
      - cert

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ../data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ../data/wordpress
      o: bind
      type: none
  
networks:
  inception:
    name: inception


secrets:
  mdb_pw:
    file: /Users/${USERNAME}/secrets/db_password.txt
  mdb_root_pw:
    file: /Users/${USERNAME}/secrets/db_root_password.txt
  wp_admin_pw:
    file: /Users/${USERNAME}/secrets/wp_root_password.txt
  wp_user_pw:
    file: /Users/${USERNAME}/secrets/wp_user_password.txt
  cert:
    file: /Users/${USERNAME}/secrets/inception.crt
  key:
    file: /Users/${USERNAME}/secrets/inception.key
